config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/home'

  get 'static_pages/help'
  
  get 'static_pages/about'
  
  get 'static_pages/contact'
  

  root 'static_pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def helloWorld
    render text: "Hello World!!!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  layout 'application'
  def home
    @test="Test"
  end

  def help
  end
  
  def about
  end
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h5>
<%= yield %>
<p>
  Navigation:
  <%= link_to "Home",static_pages_home_path%>
  <%= link_to "Help",static_pages_help_path%>
  <%= link_to "About",static_pages_about_path%>
  <%= link_to "Contact",static_pages_contact_path%>
</p>
</h5>
</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About")%>
<h1>About</h1>
<p>
    The <a href="http://www.railstutorial.org/"><em>Ruby on Rails Tutorial</em></a>
    is a <a href="http://www.railstutorial.org/book">book</a> and
    <a href ="http://screencasts.railstutorial.org/">screencas series</a>
    to teach web developmentn with
    <a href = "http://rubyonrails.org/">Ruby on Rails</a>.
    This is a sdsdsdsd sample application for the tutorial.
    </p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact")%>
<h1>Contact</h1>
<p>
     
     Email: hanspeter@gmail.de </br>
     Telefon: 000/00000 </br>
     Adress: TestStreet 87 ,Dublin 8 </br>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help")%>
<h1>Help</h1>
<p>
     Get help on the Ruby on Rails Tutorial at the
    <a href="http://www.railstutorial.org/#help">Rails Turotial help section</a>
    To get help on this sample app, see the
    <a href="http://www.railstutorial.org/book"><em>Ruby on Rails TUtorial</em>book</a>
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<h1>Sample App</h1>
<p>
    This is the home page for the
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application
</p>